# This is called after the deployed environment is ready to be checked
name: Check links
on:
  workflow_call:
    inputs:
      env_url:
        required: true
        type: string

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:

      - name: Check links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: ${{ inputs.env_url }}
          cmd_params: '--buffer-size=8192 --max-connections-per-host=10 --color=always --header="User-Agent:curl/7.54.0" --rate-limit=1' 
